# Generated by Django 4.1 on 2022-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Category image')),
            ],
            options={
                'verbose_name': 'Caregory',
                'verbose_name_plural': 'Caregories',
            },
        ),
    ]
