# Generated by Django 4.1 on 2022-08-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='history',
            field=models.TextField(null=True, verbose_name='Car history'),
        ),
    ]
